services:
  xwiki:
    image: xwiki:15.10.10-postgres-tomcat
    container_name: xwiki-vuln
    ports:
      - "8080:8080"
    environment:
      XWIKI_DB_HOST: postgres
      XWIKI_DB_DATABASE: xwiki
      XWIKI_DB_USER: xwiki
      XWIKI_DB_PASSWORD: xwiki
      DB_HOST: postgres
    depends_on:
      - postgres
    volumes:
      - xwiki-data:/var/lib/xwiki
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  postgres:
    image: postgres:13
    container_name: xwiki-postgres
    environment:
      POSTGRES_USER: xwiki
      POSTGRES_PASSWORD: xwiki
      POSTGRES_DB: xwiki
    volumes:
      - postgres-data:/var/lib/postgresql/data

  gitlab:
    image: gitlab/gitlab-ce:16.11.0-ce.0
    container_name: gitlab-lab
    ports:
      - "80:80"
      - "2222:22"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.local'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
      - legal-files:/legal-files

  attacker:
    image: nginx:alpine
    container_name: attacker-server
    ports:
      - "8000:80"
    volumes:
      - ./attacker/www:/usr/share/nginx/html:ro

volumes:
  xwiki-data:
  postgres-data:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
  legal-files: